import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY
  ? new Resend(process.env.RESEND_API_KEY)
  : null;

interface AuditEmailData {
  url: string;
  score: number;
  grade: string;
  topIssues: string[];
  reportUrl: string;
  type: 'web' | 'github';
}

export async function sendAuditReportEmail(
  to: string,
  data: AuditEmailData
): Promise<boolean> {
  if (!resend) {
    console.log('[Email] Resend not configured, skipping email');
    return false;
  }

  try {
    const subject =
      data.type === 'web'
        ? `Your AuditIQ Report for ${data.url} is ready`
        : `Your Code Review for ${data.url} is ready`;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="margin:0;padding:0;background:#0f172a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
        <div style="max-width:600px;margin:0 auto;padding:40px 20px;">
          <!-- Header -->
          <div style="text-align:center;margin-bottom:32px;">
            <div style="display:inline-block;padding:8px 16px;background:linear-gradient(135deg,#3b82f6,#8b5cf6);border-radius:8px;margin-bottom:16px;">
              <span style="color:white;font-size:20px;font-weight:bold;">A</span>
            </div>
            <h1 style="color:white;font-size:24px;margin:0;">AuditIQ Report</h1>
          </div>

          <!-- Score Badge -->
          <div style="text-align:center;margin-bottom:32px;padding:24px;background:#1e293b;border-radius:16px;">
            <p style="color:#94a3b8;font-size:14px;margin:0 0 8px 0;">Overall Score</p>
            <div style="display:inline-block;padding:12px 24px;background:${data.score >= 80 ? '#166534' : data.score >= 50 ? '#854d0e' : '#991b1b'};border-radius:12px;">
              <span style="color:white;font-size:32px;font-weight:bold;">${data.score}</span>
              <span style="color:#d1d5db;font-size:16px;">/100</span>
            </div>
            <p style="color:#94a3b8;font-size:14px;margin:12px 0 0 0;">Grade: <strong style="color:white;">${data.grade}</strong></p>
          </div>

          <!-- URL -->
          <div style="padding:16px;background:#1e293b;border-radius:12px;margin-bottom:24px;">
            <p style="color:#94a3b8;font-size:12px;margin:0 0 4px 0;text-transform:uppercase;">${data.type === 'web' ? 'Website' : 'Repository'}</p>
            <p style="color:white;font-size:14px;margin:0;word-break:break-all;">${data.url}</p>
          </div>

          <!-- Top Issues -->
          ${data.topIssues.length > 0 ? `
          <div style="margin-bottom:24px;">
            <h2 style="color:white;font-size:16px;margin:0 0 12px 0;">Key Findings</h2>
            ${data.topIssues.map((issue) => `
              <div style="padding:12px 16px;background:#1e293b;border-left:3px solid #f59e0b;border-radius:0 8px 8px 0;margin-bottom:8px;">
                <p style="color:#e2e8f0;font-size:14px;margin:0;">${issue}</p>
              </div>
            `).join('')}
          </div>
          ` : ''}

          <!-- CTA Button -->
          <div style="text-align:center;margin:32px 0;">
            <a href="${data.reportUrl}" style="display:inline-block;padding:14px 32px;background:linear-gradient(135deg,#3b82f6,#8b5cf6);color:white;text-decoration:none;border-radius:12px;font-weight:bold;font-size:16px;">
              View Full Report
            </a>
          </div>

          <!-- Footer -->
          <div style="text-align:center;padding-top:24px;border-top:1px solid #334155;">
            <p style="color:#64748b;font-size:12px;margin:0;">
              Generated by AuditIQ — Website & Code Audit Tool
            </p>
            <p style="color:#475569;font-size:11px;margin:8px 0 0 0;">
              <a href="https://auditiq.com/unsubscribe" style="color:#64748b;">Unsubscribe</a>
            </p>
          </div>
        </div>
      </body>
      </html>
    `;

    await resend.emails.send({
      from: process.env.FROM_EMAIL || 'reports@auditiq.com',
      to,
      subject,
      html,
    });

    console.log(`[Email] Report sent to ${to} for ${data.url}`);
    return true;
  } catch (error) {
    console.error('[Email] Failed to send:', error);
    return false;
  }
}
